### ISSUE TITLE
Support for ltx-video-2b-v0.9.1

### ISSUE THREAD

**Issue by Jandown** [newgenai79/newgenai#2]
Thank you for sharing
0.91 has a smaller volume, but replacing it directly will result in an error. We hope it can be supported.

**Comment by nitinmukesh** [comment]
Code is ready, just waiting for LTX team to create the hugging face repo.

**Comment by newgenai79** [comment]
@Jandown 

Here you go
https://youtu.be/L8hkDNPacFw

**Comment by Jandown** [comment]
> @Jandown
> 
> Here you go  给你 https://youtu.be/L8hkDNPacFw

Thanks
