### ISSUE TITLE
please make sure to pass both low_cpu_mem_usage=False and ignore_mismatched_sizes=True

### ISSUE THREAD

**Issue by J-Ai-57** [newgenai79/newgenai#7]
![Screenshot 2024-12-25 230620](https://github.com/user-attachments/assets/fdb90ba8-8be9-45c8-9dda-a6eb226de428)

**Comment by J-Ai-57** [comment]
has anyone solved this issue?

**Comment by nitinmukesh** [comment]
It seems you don't have CUDA 12.4 or above installed

share output of 
1. Activate virtual environment
2. pip list

and output of
nvcc --version

copy paste the output, do not paste screenshot

**Comment by J-Ai-57** [comment]
Package            Version
------------------ ------------
accelerate         1.2.1
aiofiles           23.2.1
annotated-types    0.7.0
anyio              4.7.0
certifi            2024.12.14
charset-normalizer 3.4.0
click              8.1.8
colorama           0.4.6
diffusers          0.32.0.dev0
einops             0.8.0
fastapi            0.115.6
ffmpy              0.5.0
filelock           3.16.1
fsspec             2024.12.0
gguf               0.13.0
gradio             5.9.1
gradio_client      1.5.2
h11                0.14.0
httpcore           1.0.7
httpx              0.28.1
huggingface-hub    0.25.2
idna               3.10
imageio            2.36.1
imageio-ffmpeg     0.5.1
importlib_metadata 8.5.0
Jinja2             3.1.5
markdown-it-py     3.0.0
MarkupSafe         2.1.5
mdurl              0.1.2
mpmath             1.3.0
networkx           3.4.2
numpy              2.2.0
opencv-python      4.10.0.84
orjson             3.10.12
packaging          24.2
pandas             2.2.3
pillow             11.0.0
pip                24.0
psutil             6.1.1
pydantic           2.10.4
pydantic_core      2.27.2
pydub              0.25.1
Pygments           2.18.0
python-dateutil    2.9.0.post0
python-multipart   0.0.20
pytz               2024.2
PyYAML             6.0.2
regex              2024.11.6
requests           2.32.3
rich               13.9.4
ruff               0.8.4
safehttpx          0.1.6
safetensors        0.4.5
semantic-version   2.10.0
sentencepiece      0.2.0
setuptools         65.5.0
shellingham        1.5.4
six                1.17.0
sniffio            1.3.1
starlette          0.41.3
sympy              1.13.1
tokenizers         0.21.0
tomlkit            0.13.2
torch              2.5.1+cu124
torchvision        0.20.1+cu124
tqdm               4.67.1
transformers       4.47.1
typer              0.15.1
typing_extensions  4.12.2
tzdata             2024.2
urllib3            2.2.3
uvicorn            0.34.0
websockets         14.1
wheel              0.45.1
zipp               3.21.0

**Comment by nitinmukesh** [comment]
@J-Ai-57 

nvcc --version

**Comment by J-Ai-57** [comment]
getting "nvcc is not a recognised as internal or external command

**Comment by nitinmukesh** [comment]
Cool.

Install it
https://developer.nvidia.com/cuda-downloads

**Comment by J-Ai-57** [comment]
D:\newgenai>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Oct_30_01:18:48_Pacific_Daylight_Time_2024
Cuda compilation tools, release 12.6, V12.6.85
Build cuda_12.6.r12.6/compiler.35059454_0

**Comment by nitinmukesh** [comment]
Now it should work

**Comment by J-Ai-57** [comment]
will try again. Thanks

**Comment by J-Ai-57** [comment]
(venv) D:\newgenai\LTX>python LTX091_I2V_gradio.py
Successfully downloaded: model_index.json
Successfully downloaded: scheduler/scheduler_config.json
Successfully downloaded: text_encoder/config.json
Successfully downloaded: text_encoder/model-00001-of-00004.safetensors
Successfully downloaded: text_encoder/model-00002-of-00004.safetensors
Successfully downloaded: text_encoder/model-00003-of-00004.safetensors
Successfully downloaded: text_encoder/model-00004-of-00004.safetensors
Successfully downloaded: text_encoder/model.safetensors.index.json
Successfully downloaded: tokenizer/added_tokens.json
Successfully downloaded: tokenizer/special_tokens_map.json
Successfully downloaded: tokenizer/spiece.model
Successfully downloaded: tokenizer/tokenizer_config.json
Successfully downloaded: transformer/config.json
Successfully downloaded: transformer/diffusion_pytorch_model.safetensors
Successfully downloaded: vae/config.json
Successfully downloaded: vae/diffusion_pytorch_model.safetensors
Successfully downloaded: ltx-video-2b-v0.9.1.safetensors
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.13s/it]
Loading pipeline components...:  80%|█████████████████████████████████████████▌          | 4/5 [00:00<00:00, 11.55it/s]
Traceback (most recent call last):
  File "D:\newgenai\LTX\LTX091_I2V_gradio.py", line 139, in <module>
    pipe = LTXImageToVideoPipeline.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\loaders\single_file.py", line 495, in from_single_file
    loaded_sub_model = load_single_file_sub_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\loaders\single_file.py", line 102, in load_single_file_sub_model
    loaded_sub_model = load_method(
                       ^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\loaders\single_file_model.py", line 349, in from_single_file
    unexpected_keys = load_model_dict_into_meta(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\newgenai\venv\Lib\site-packages\diffusers\models\model_loading_utils.py", line 230, in load_model_dict_into_meta
    raise ValueError(
ValueError: Cannot load  because decoder.conv_in.conv.bias expected shape tensor(..., device='meta', size=(512,)), but got torch.Size([1024]). If you want to instead overwrite randomly initialized weights, please make sure to pass both `low_cpu_mem_usage=False` and `ignore_mismatched_sizes=True`. For more information, see also: https://github.com/huggingface/diffusers/issues/1619#issuecomment-1345604389 as an example.

(venv) D:\newgenai\LTX>

**Comment by nitinmukesh** [comment]
Did you launched a new command prompt after installing CUDA? If not close the command prompt and launch again as environment variables will not be reflected.

**Comment by J-Ai-57** [comment]
Issue fixed after re-installing requirements.txt. Thanks for your help 😊

**Comment by newgenai79** [comment]
Thanks for confirming.
